[project]
name = "regulaitor"
version = "0.1.0"
description = "Stay in compliance with the power of AI"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "beautifulsoup4>=4.12.3",
    "scrapy-playwright>=0.0.41", 
    "scrapy>=2.11.2",
    "pyautogen>=0.2",
    "tenacity",
    "flaml[automl]"
]

[dependency-groups]
dev = [
    "black>=24.10.0",
    "isort>=5.13.2",
]
