[project]
name = "regulaitor"
version = "0.1.0"
description = "Stay in compliance with the power of AI"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
  "beautifulsoup4>=4.12.3",
  "scrapy-playwright>=0.0.41",
  "scrapy>=2.11.2",
  "loguru>=0.7.2",
  "qdrant-client>=1.12.1",
  "dspy>=2.5.41",
  "autogen>=0.4",
  "torch>=2.5.1",
]

[dependency-groups]
dev = ["black>=24.10.0", "isort>=5.13.2"]

[project.scripts]
warning-letter-state-machine-example = "regulaitor.Framework:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.uv.sources]
torch = [
  { index = "pytorch-cpu", marker = "platform_system == 'Windows'" },
  { index = "pytorch-cu124", marker = "platform_system == 'Linux'" },
]
torchvision = [
  { index = "pytorch-cpu", marker = "platform_system == 'Windows'" },
  { index = "pytorch-cu124", marker = "platform_system == 'Linux'" },
]

[[tool.uv.index]]
name = "pytorch-cpu"
url = "https://download.pytorch.org/whl/cpu"
explicit = true

[[tool.uv.index]]
name = "pytorch-cu124"
url = "https://download.pytorch.org/whl/cu124"
explicit = true
